"""Pydantic models describing aijournal's authoritative and derived artifacts."""

from __future__ import annotations

from .authoritative import (
    ClaimsFile,
    JournalEntry,
    JournalSection,
    JsonScalar,
    JsonValue,
    ManifestEntry,
    NormalizedEntity,
    NormalizedEntry,
    SelfProfile,
)
from .base import AijournalModel
from .claim_atoms import (
    ClaimAtom,
    ClaimAtomsFile,
    ClaimMethod,
    ClaimSource,
    ClaimSourceSpan,
    ClaimStatus,
    ClaimType,
    Provenance,
    Scope,
)
from .derived import (
    AdviceCard,
    AdviceRecommendation,
    AdviceReference,
    ChunkManifest,
    ChunkManifestChunk,
    ChunkManifestMeta,
    ClaimConflictPayload,
    ClaimPreviewEvent,
    ClaimProposal,
    ClaimSignaturePayload,
    DailySummary,
    FacetChange,
    FactEvidence,
    FactEvidenceSpan,
    FeedbackAdjustmentEvent,
    FeedbackBatch,
    IndexMeta,
    InterviewQuestion,
    InterviewSet,
    MicroFact,
    MicroFactsFile,
    PersonaCore,
    PersonaCoreFile,
    PersonaCoreMeta,
    ProfileSuggestions,
    ProfileSuggestionUpdate,
    ProfileSuggestionUpsert,
    ProfileUpdateBatch,
    ProfileUpdateInput,
    ProfileUpdatePreview,
    ProfileUpdateProposals,
    SummaryMeta,
)
from .responses import AdviceLLMResponse

Claim = ClaimAtom

__all__ = [
    "AdviceCard",
    "AdviceLLMResponse",
    "AdviceRecommendation",
    "AdviceReference",
    "AijournalModel",
    "Claim",
    "ClaimAtom",
    "ClaimAtomsFile",
    "ClaimConflictPayload",
    "ClaimMethod",
    "ClaimPreviewEvent",
    "ClaimProposal",
    "ClaimSignaturePayload",
    "ClaimSource",
    "ClaimSourceSpan",
    "ClaimStatus",
    "ClaimType",
    "ChunkManifest",
    "ChunkManifestChunk",
    "ChunkManifestMeta",
    "ClaimsFile",
    "DailySummary",
    "FeedbackAdjustmentEvent",
    "FeedbackBatch",
    "FactEvidence",
    "FactEvidenceSpan",
    "FacetChange",
    "IndexMeta",
    "InterviewQuestion",
    "InterviewSet",
    "JournalEntry",
    "JournalSection",
    "JsonScalar",
    "JsonValue",
    "ManifestEntry",
    "MicroFact",
    "MicroFactsFile",
    "NormalizedEntry",
    "NormalizedEntity",
    "PersonaCore",
    "PersonaCoreFile",
    "PersonaCoreMeta",
    "ProfileSuggestionUpsert",
    "ProfileSuggestionUpdate",
    "ProfileSuggestions",
    "ProfileUpdateBatch",
    "ProfileUpdateInput",
    "ProfileUpdatePreview",
    "ProfileUpdateProposals",
    "Provenance",
    "Scope",
    "SelfProfile",
    "SummaryMeta",
]
